# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directassessmenttask',
            name='requiredAnnotations',
            field=models.PositiveSmallIntegerField(default=1, help_text='(value in range=[1,5])', verbose_name='Required annotations'),
            preserve_default=False,
        ),
    ]
