# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EvalData', '0002_directassessmenttask_requiredannotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='directassessmenttask',
            name='assignedTo',
            field=models.ForeignKey(default=None, help_text='(user working on this task)', on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmenttask_assignedTo', related_query_name='evaldata_directassessmenttasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directassessmenttask',
            name='requiredAnnotations',
            field=models.PositiveSmallIntegerField(help_text='(value in range=[1,50])', verbose_name='Required annotations'),
        ),
    ]
