# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0004_directassessmenttask_batchno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directassessmenttask',
            name='assignedTo',
            field=models.ForeignKey(blank=True, help_text='(user working on this task)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmenttask_assignedTo', related_query_name='evaldata_directassessmenttasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
