# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0002_auto_20170501_1437'),
        ('EvalData', '0005_auto_20170602_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='directassessmenttask',
            name='batchData',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmenttask_campaigndata', related_query_name='evaldata_directassessmenttasks', to='Campaign.CampaignData', verbose_name='Campaign data'),
            preserve_default=False,
        ),
    ]
