# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0008_auto_20170602_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='source',
            field=models.CharField(help_text='(max. 5000 characters)', max_length=5000, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='sourceText',
            field=models.CharField(help_text='(max. 5000 characters)', max_length=5000, verbose_name='Source text'),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='targetText',
            field=models.CharField(help_text='(max. 5000 characters)', max_length=5000, verbose_name='Target text'),
        ),
        migrations.AlterField(
            model_name='textsegment',
            name='segmentText',
            field=models.CharField(help_text='(max. 5000 characters)', max_length=5000, verbose_name='Segment text'),
        ),
    ]
