# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0009_auto_20170602_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpair',
            name='sourceID',
            field=models.CharField(help_text='(max. 250 characters)', max_length=250, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='targetID',
            field=models.CharField(help_text='(max. 250 characters)', max_length=250, verbose_name='Target ID'),
        ),
        migrations.AlterField(
            model_name='textsegment',
            name='segmentID',
            field=models.CharField(help_text='(max. 250 characters)', max_length=250, verbose_name='Segment ID'),
        ),
    ]
