# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0010_auto_20170602_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='directassessmenttask',
            name='currentItemNo',
            field=models.PositiveIntegerField(default=1, help_text='(1-based)', verbose_name='Current item number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directassessmenttask',
            name='batchNo',
            field=models.PositiveIntegerField(help_text='(1-based)', verbose_name='Batch number'),
        ),
    ]
