# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EvalData', '0012_auto_20170602_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directassessmenttask',
            name='currentItemNo',
        ),
        migrations.RemoveField(
            model_name='directassessmenttask',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='directassessmenttask',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, help_text='(users working on this task)', null=True, related_name='evaldata_directassessmenttask_assignedTo', related_query_name='evaldata_directassessmenttasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
