# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0013_auto_20170604_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='directassessmentresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentresult_task', related_query_name='evaldata_directassessmentresults', to='EvalData.DirectAssessmentTask', verbose_name='Task'),
        ),
    ]
