# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0015_auto_20170605_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='source',
            field=models.CharField(help_text='(max. 2000 characters)', max_length=2000, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='sourceID',
            field=models.CharField(help_text='(max. 1000 characters)', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='sourceText',
            field=models.CharField(help_text='(max. 2000 characters)', max_length=2000, verbose_name='Source text'),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='targetID',
            field=models.CharField(help_text='(max. 1000 characters)', max_length=1000, verbose_name='Target ID'),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='targetText',
            field=models.CharField(help_text='(max. 2000 characters)', max_length=2000, verbose_name='Target text'),
        ),
        migrations.AlterField(
            model_name='textsegment',
            name='segmentID',
            field=models.CharField(help_text='(max. 1000 characters)', max_length=1000, verbose_name='Segment ID'),
        ),
        migrations.AlterField(
            model_name='textsegment',
            name='segmentText',
            field=models.CharField(help_text='(max. 2000 characters)', max_length=2000, verbose_name='Segment text'),
        ),
    ]
