# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0016_auto_20170605_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directassessmenttask',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='(users working on this task)', related_name='evaldata_directassessmenttask_assignedTo', related_query_name='evaldata_directassessmenttasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
