# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Campaign', '0005_trusteduser'),
        ('EvalData', '0019_auto_20170619_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign.Campaign', verbose_name='Campaign')),
                ('completedTasks', models.ManyToManyField(related_name='evaldata_workagenda_completedtasks', related_query_name='evaldata_workagendas', to='EvalData.DirectAssessmentTask', verbose_name='Completed tasks')),
                ('openTasks', models.ManyToManyField(related_name='evaldata_workagenda_opentasks', related_query_name='evaldata_workagendas', to='EvalData.DirectAssessmentTask', verbose_name='Open tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
