# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0021_auto_20171005_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workagenda',
            name='completedTasks',
            field=models.ManyToManyField(blank=True, related_name='evaldata_workagenda_completedtasks', related_query_name='evaldata_workagendas_completed', to='EvalData.DirectAssessmentTask', verbose_name='Completed tasks'),
        ),
        migrations.AlterField(
            model_name='workagenda',
            name='openTasks',
            field=models.ManyToManyField(blank=True, related_name='evaldata_workagenda_opentasks', related_query_name='evaldata_workagendas_open', to='EvalData.DirectAssessmentTask', verbose_name='Open tasks'),
        ),
    ]
