# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0026_auto_20171006_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='textpair',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='textpairwithimage',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='textsegment',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
