# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0027_auto_20171006_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='directassessmentresult',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='directassessmenttask',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='market',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='multimodalassessmentresult',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='multimodalassessmenttask',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
