# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0028_auto_20171006_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directassessmentresult',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentresult_item', related_query_name='evaldata_directassessmentresults', to='EvalData.TextPair', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='directassessmentresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentresult_task', related_query_name='evaldata_directassessmentresults', to='EvalData.DirectAssessmentTask', verbose_name='Task'),
        ),
    ]
