# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0030_objectid_taskagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskagenda',
            name='strategy',
            field=models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], default='M', max_length=1, verbose_name='Strategy'),
        ),
    ]
