# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0032_taskagenda_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectid',
            name='_str_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
